language: cpp
compiler:
  - gcc
env:
  - CONFIG=debug QT=Qt5
  - CONFIG=release QT=Qt5

before_install:
  - if [ $QT == "Qt5" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa; fi
  - sudo apt-get update
install:
  - if [ $QT == "Qt4" ]; then sudo apt-get install libqt4-dev qt4-qmake libqt4-sql-sqlite; fi
  - if [ $QT == "Qt5" ]; then sudo apt-get install -y qt5-default libqt5sql5-sqlite; fi
  - Travis/quazip.sh

script:
  - mkdir Sources/build
  - cd Sources/build
  - qmake QMAKE_CXX=$CXX CONFIG+=$CONFIG ../ProjetVaR.pro
  - make
  - export LD_LIBRARY_PATH=ModelVaR
  - cp ../quazip/build/libquazip.so* ModelVaR/
  - TestUnitaire/main
  - cd ../..
  - python Travis/conventions.py Sources/ModelVaR/ Sources/TestUnitaire/ Sources/GUI/

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks: http://zebil.dnsdynamic.com/travis.php
