before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libqt4-dev qt4-qmake libqt4-sql-sqlite

script:
  - mkdir build
  - cd build
  - qmake ../ProjetVaR_Software/ProjetVaR_Software.pro
  - make
  - export LD_LIBRARY_PATH=ModelVaR
  - TestUnitaire/main

notifications:
  email:
    recipients:
      - paul.chaignon@insa-rennes.fr
    on_success: never
    on_failure: change